### PR TITLE
fix(toggle): toggle state with synced UI instead of only in DB

### LINKED ISSUE #110: [BUG] Toggle state toggles in db instead of local state
Instead of toggling in the database, we should try to toggle based on the current local browser state (if the user sees "outside" and tries to toggle, it should try to put the person inside instead of toggling whatever is the current state in db).

This would solve a problem when 2 users try to toggle the same person at the same time.

### LINKED ISSUE #218: [BUG] Toggle guest fails in the same browser session
When you admit a guest, by choosing a guarantor, it saves the guarantor in a Svelte store (which remains in one browser session) and then that same guarantor gets checked if it's valid when releasing the guest which in turn disallows you to release a guest since the guarantor has hit the limit (for example 1 max guests per guarantor).

This is worked around by refreshing the page.

### PR DESCRIPTION
**Pull request by filipvidakovic**
Closes #110 
Closes #218

This pull request includes changes to add an `action` parameter to the `togglePersonState` function and its associated forms and calls. This parameter is used to specify whether a person should be "admitted" or "released". The most important changes include updates to the function definition, form schemas, and form handling logic.

### Function updates:
* [`src/lib/server/db/person.ts`](diffhunk://#diff-a5a18ee5ab00b24ef000336f26654a48302d183d57d97c56de1f38398cccf0e0R828): Added an `action` parameter to the `togglePersonState` function and included logic to handle "admit" and "release" actions. [[1]](diffhunk://#diff-a5a18ee5ab00b24ef000336f26654a48302d183d57d97c56de1f38398cccf0e0R828) [[2]](diffhunk://#diff-a5a18ee5ab00b24ef000336f26654a48302d183d57d97c56de1f38398cccf0e0R841) [[3]](diffhunk://#diff-a5a18ee5ab00b24ef000336f26654a48302d183d57d97c56de1f38398cccf0e0R886-R887) [[4]](diffhunk://#diff-a5a18ee5ab00b24ef000336f26654a48302d183d57d97c56de1f38398cccf0e0R943-R944)

### Form schema updates:
* [`src/routes/(dashboard)/schema.ts`](diffhunk://#diff-5369aed1ea92566dd1abf1567f2ca29728d4ad50cc6a8e15044457c512e30139L15-R29): Updated the `toggleStateFormSchema` and `toggleGuestStateFormSchema` to include the `action` parameter with validation to ensure it is either "admit" or "release".

### Form handling updates:
* [`src/lib/stores/toggleState.svelte.ts`](diffhunk://#diff-73b54f0a299b03086d0a7fa28eb8b302c6f5317be7a8f0b835c0706ef6dcd226R4-R8): Added the `action` field to the `toggleStateFormStore`.
* [`src/routes/(dashboard)/+page.server.ts`](diffhunk://#diff-5573a1cb627518ff8fcadb674e30b2debe7cbba9ca73f698f751d20c553ce33aR120): Updated the form handling logic to include the `action` parameter when calling `togglePersonState`. [[1]](diffhunk://#diff-5573a1cb627518ff8fcadb674e30b2debe7cbba9ca73f698f751d20c553ce33aR120) [[2]](diffhunk://#diff-5573a1cb627518ff8fcadb674e30b2debe7cbba9ca73f698f751d20c553ce33aL128-R134) [[3]](diffhunk://#diff-5573a1cb627518ff8fcadb674e30b2debe7cbba9ca73f698f751d20c553ce33aL171-R177)
* [`src/routes/(dashboard)/+page.svelte`](diffhunk://#diff-8081ead867958d5efae926292693aec1ddcc2e4294022da358037f8ae4c32555R358-R365): Added hidden form fields for the `action` parameter to ensure it is included in form submissions. [[1]](diffhunk://#diff-8081ead867958d5efae926292693aec1ddcc2e4294022da358037f8ae4c32555R358-R365) [[2]](diffhunk://#diff-8081ead867958d5efae926292693aec1ddcc2e4294022da358037f8ae4c32555R386-R393)
* [`src/routes/(dashboard)/data-table-actions.svelte`](diffhunk://#diff-d969550543079977eaec0fb4160713988b5a8f9f8e1861620f588b33a2193be4R39): Set the `action` parameter in the `toggleStateFormStore` based on user actions. [[1]](diffhunk://#diff-d969550543079977eaec0fb4160713988b5a8f9f8e1861620f588b33a2193be4R39) [[2]](diffhunk://#diff-d969550543079977eaec0fb4160713988b5a8f9f8e1861620f588b33a2193be4R49) [[3]](diffhunk://#diff-d969550543079977eaec0fb4160713988b5a8f9f8e1861620f588b33a2193be4R66) [[4]](diffhunk://#diff-d969550543079977eaec0fb4160713988b5a8f9f8e1861620f588b33a2193be4R77) [[5]](diffhunk://#diff-d969550543079977eaec0fb4160713988b5a8f9f8e1861620f588b33a2193be4R87-R92) [[6]](diffhunk://#diff-d969550543079977eaec0fb4160713988b5a8f9f8e1861620f588b33a2193be4R107-R112)

### CODE REVIEW

**Comment by filipvidakovic** [comment]
Close #110

File: src/lib/server/db/person.ts [hunk 1]
```diff
@@ -825,6 +825,7 @@ export async function togglePersonState(
 	id: number,
 	building: string,
 	creator: string,
+	action: string,
```
Comment (aleksasiriski) [inline src/lib/server/db/person.ts:828]: Make this not be type `string` but instead literal `'admit' | 'release'`

File: src/lib/server/db/person.ts [hunk 2]
```diff
@@ -837,6 +838,10 @@ export async function togglePersonState(
 		throw new Error('Invalid creator (empty)');
 	}
 
+	if (action !== 'admit' && action !== 'release') {
```
Comment (aleksasiriski) [inline src/lib/server/db/person.ts:841]: With above this isn't needed

**Review by aleksasiriski — CHANGES_REQUESTED** [review]
Haven't checked the PR in detail but a few minor changes, also did you forget to include `transfer` as an action?

File: src/lib/server/db/person.ts [hunk 3]
```diff
@@ -886,8 +882,8 @@ export async function togglePersonState(
 
 			// Toggle the person state
 			if (isInside(entryTimestamp, exitTimestamp)) {
-				if (action !== 'release') throw new Error('Person is already inside');
 				if (building === entryBuilding) {
+					if (action !== 'release') throw new Error('Person is already inside');
```
Comment (aleksasiriski) [inline src/lib/server/db/person.ts:886]: Should say already outside?

**Review by aleksasiriski — COMMENTED** [review]
Are the messages correct?

File: src/lib/server/db/person.ts (hunk 3 above)
Comment (filipvidakovic) [reply src/lib/server/db/person.ts:886]: the if above deducts that the person is inside and if the action isn't release we send message that person is inside and can't be admitted or transfered

Comment (filipvidakovic) [reply src/lib/server/db/person.ts:886]: Maybe I should only change the format of the message, for example: "Can't perform {$action}, person is inside", if that's what you thought.

**Comment by filipvidakovic** [comment]
Please check again, it's a bit confusing

File: src/lib/server/db/person.ts [hunk 4]
```diff
@@ -892,7 +893,8 @@ export async function togglePersonState(
 					});
 					return StateOutside;
 				} else {
-					if (action !== 'transfer') throw new Error('Person is already in another building');
+					if (action !== 'transfer')
+						throw new Error(`Can't perform ${action}, person is already in another building`);
```
Comment (aleksasiriski) [inline src/lib/server/db/person.ts:897]: `has already been transfered` might be better here

**Review by aleksasiriski — APPROVED** [review]
